# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 912f0a6ca9a45c889de50674d0d3b9dcdea8d0e78d322ae0b0e7c8597897bef17bcd7c221c6ba91e998a8d981c884bbc65e28215ece3b4e7d0eca3860793bbc8

test:
  secret_key_base: e1a2070087d7f7b1bd01f37180048f8a1b11a2d2c5ec505591b865fea7d8e686fd01e99d231ba57e332a9b1edf472b9be9433ae0d4b2ff2214c488cb7bacaafa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
