# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc95cf67e26134454482e419019ed458d09c8004f5abfcb950a128b806efc0d961c40ad834b7ce12a09faa82cfc4817c506be79be462249ddf02c698c47be598

test:
  secret_key_base: 2fa80a1d6dc634e1f1f37e1582a3eb12f77ade4913a6bef6add560d330be597e3723f7e8bfbe1e875ff7a805e1ca1ca52f7211fc4eb2da55019a83aad3f5a138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
