# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25bc3068c5156576c5187a6afebb0bc12fa0038966ab1d3e4b6f8a25a0ee795933d0eb22e20aa1491ace100b13bdf31749097360df7cf285378c040a21eeadb5

test:
  secret_key_base: e829929966d7eaee3ef00b8e9d00e319a660865cca065161b0085dc6046b66737cada9284eb66540aa370a0692402507f09c11cb01b554bced959668649e6a53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
